apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
#      nodeName: c77k8s4
      containers:
        - name: nginx
          image: nginx:latest
#          image: viejo/curl:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
#apiVersion: v1
#kind: Service
#metadata:
#  me: nginx-service-nodeport
#spec:
#  ports:
#    - port: 80
#      targetPort: 80
#      protocol: TCP
#  type: NodePort
#  selector:
#    name: nginx
